acme/urls.py
from django.conf import settings
from django.conf.urls import url, include, handler404, handler500
from django.contrib import admin

from . import views

handler404 ='acme.views.handler404'
handler404 ='acme.views.handler500'

urlpatterns = [
     url(r'^$', views.home, name='home'),

      url(r'^$', include('account.urls')),

     url(r'^about/', views.about, name='about'),

     url(r'^contact/', views.contact, name='contact'),

     url(r'^blog/', include('blog.urls')),

     url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        #path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
         url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

blog/urls.py
from django.conf.urls import url

from . import views
app_name = 'blog'

urlpatterns = [
     url(r'^$', views.index, name='index'),

     url(r'^posts/(?P<id>[0-9]+)$', views.show, name='show'),
]

blog/models.py
from django.db import models

# Create your models here.
class TimespamtedModel(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True
			


class Post(TimespamtedModel):
	title = models.CharField(max_length=255)
	body = models.TextField()


	def __str__(self):
		return self.title

acme/views.py
from django.shortcuts import render

def home(request):
   return render(request, 'pages/home.html')


def about(request):
   return render(request, 'pages/about.html')



def contact(request):
   return render(request, 'pages/contact.html')

def handler404(request, exception=None):
   return render(request, 'errors/404.html')

def handler500(request, exception=None):
   return render(request, 'errors/500.html')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404


#from .mocks import Post
from .models import Post

#posts= [

	#{'id': 1, 'title': 'First Post', 'body': 'This is my first post'},
	#{'id': 2, 'title': 'Second Post', 'body': 'This is my second post'},
	#{'id': 3, 'title': 'Third Post', 'body': 'This is my this post'},
#]


# Create your views here.



def index(request):
	posts = Post.objects.all()
	return render(request, 'blog/index.html', {'posts': posts})


def show(request,id):
	post = get_object_or_404(Post, pk=id)
	#try:
		#post = Post.objects.get(pk=id)
	#except Post.DoesNotExist:
		#raise Http404('Sorry the post #{} was not found.' .format(id))

	return render(request, 'blog/show.html', {'post': post})

blog/templates/blog/base.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block stylesheets %}

	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/styles.css'%}">
	
{% endblock %}

{% block content %} 

	<h1>Blog</h1>

	{% block body %} {% endblock %}


{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html'%}

{% load static %}

{% block title %} Blog {% endblock %}


{% block body %} 

	
	<h1> {{ posts|length }} posts </h1>


	{% for post in posts %}

			<article>

			<h2 class="title">
			 <a href="{% url 'blog:show' post.id %}">#{{post.id}}-{{post.title}} </a>
			</h2>

			
			<p class="time"> 

				<time datetime="{{post.created_at|date:'Y-m-d'}}">Posted {{post.created_at|timesince}} ago


				</time>

			</p>

			<p class="content">{{post.body | truncatewords:3}}

			</p>

			</article>


	{% empty %}

		<p> No post available </p>

	{% endfor %}
{% endblock %}

blog/templates/blog/show.html
{% extends 'blog/base.html'%}

{% block title %}Blog | {{ post.title }}{% endblock %}

{% block body %}
	<article>
		<h1 class="title">#{{post.id }} - {{ post.title }} </h1>

		<p class="content"> {{ post.body }} </p>
	</article>

	<p><a href="{% url 'blog:index'%}">All Posts</a></p>
{% endblock %}

templates/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title> {% block title %} Diallo {% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
	
	{% block stylesheets %} {% endblock %}
</head>
<body>
{% include 'layouts/nav.html' %}

<div class="wrapper">
	{% block content %} {% endblock %}
</div>



{% include 'layouts/footer.html' %}

{% block javascripts %} {% endblock %}
	
</body>
</html>

templates/layouts/footer.html
<footer class="footer text-center">
	<p>hhsnxghsnnbbbn</p>
</footer>

templates/layouts/nav.html
<nav class="navbar">

	<div class="wrapper">
		<a href="{% url 'home' %}" class="navbar-brand">Diallo</a>
	
		<ul class="navbar-rigth">
			<li><a href="{% url 'home' %}">Home</a></li>
			<li><a href="{% url 'blog:index' %}">Blog</a></li>
			<li><a href="{% url 'about' %}">About</a></li>
			<li><a href="{% url 'contact' %}">Contact</a></li>
		</ul>
	</div>
	

</nav>

templates/pages/about.html
{% extends 'layouts/base.html'%}

{% block title %} About {% endblock %}

{% block content %}
	<h1> About </h1>
	<p>hjnssbn,wbjfswj,jsqjqsbjefiqjnqj.
	hqhhqsqsv</p>
{% endblock content %}

templates/pages/contact.html
{% extends 'layouts/base.html'%}

{% block title %} Contact {% endblock %}

{% block content %}
	<h1> Contact </h1>
	<p>swnk,swq,wbhbhqnnwn</p>
{% endblock content %}

templates/pages/home.html
{% extends 'layouts/base.html'%}

{% block content %} 
	<h1>hello adama </h1>

	

	<p>Bienvenue visiter notre <a href="{% url 'blog:index' %}">blogue </a>  </p>


{% endblock content %}